idf_component_register(
    SRCS 
    # -------------- IMAGES---------------
    "lv_image/lv_im_bubble_01.c"
    "lv_image/lv_im_bubble_02.c"
    "lv_image/lv_im_drop.c"
    "lv_image/lv_im_module_heat.c"
    "lv_image/lv_im_module_hotwater.c"
    "lv_image/lv_im_module_input_output.c"
    "lv_image/lv_im_module_lock.c"
    "lv_image/lv_im_module_off.c"
    "lv_image/lv_im_module_on.c"
    "lv_image/lv_im_module_podp.c"
    "lv_image/lv_im_pump_off.c"
    "lv_image/lv_im_pump_on.c"
    "lv_image/lv_im_radial_mask.c"
    "lv_image/lv_im_scale_marker.c"
    "lv_image/lv_im_scale.c"
    "lv_image/lv_im_scheme.c"
    "lv_image/lv_im_time.c"
    "lv_image/lv_im_valve_off.c"
    "lv_image/lv_im_valve_on.c"
    "lv_image/lv_im_arrow_down.c"
    "lv_image/lv_im_arrow_left.c"
    "lv_image/lv_im_arrow_right.c"
    "lv_image/lv_im_arrow_up.c"
    "lv_image/lv_im_p_arrow_up.c"
    "lv_image/lv_im_p_arrow_down.c"
    "lv_image/lv_im_comfort.c"
    "lv_image/lv_im_day.c"
    "lv_image/lv_im_hand.c"
    "lv_image/lv_im_night.c"
    "lv_image/lv_im_point_yellow_y.c"
    "lv_image/lv_im_point_yellow_x.c"
    "lv_image/lv_im_point_yellow_change_y.c"
    "lv_image/lv_im_point_yellow_change_x.c"
    "lv_image/lv_im_point_white.c"
    "lv_image/lv_im_all_in_out.c"
    "lv_image/lv_im_analog_out.c"
    "lv_image/lv_im_controller.c"
    "lv_image/lv_im_digital_out.c"
    "lv_image/lv_im_light_gray.c"
    "lv_image/lv_im_light_green.c"
    "lv_image/lv_im_light_red.c"
    "lv_image/lv_im_module_inout.c"
    "lv_image/lv_im_universal_in.c"
    "lv_image/lv_im_radius_yellow.c"
    "lv_image/lv_im_module_unlock.c"
    "lv_image/lv_im_radius_gray.c"
    "lv_image/lv_im_big_lock_open.c"
    "lv_image/lv_im_big_lock_close.c"

    "lv_image/lv_im_valve_alarm.c"
    "lv_image/lv_im_status_alarm.c"
    "lv_image/lv_im_pump_alarm.c"
    "lv_image/lv_im_module_alarms.c"
    "lv_image/lv_im_line_v_yellow.c"
    "lv_image/lv_im_line_v_white.c"
    "lv_image/lv_im_line_h_yellow.c"
    "lv_image/lv_im_line_h_white.c"
    "lv_image/lv_im_alarm_status.c"
    "lv_image/lv_im_service_icon.c"

    
    
    # ------------FONTS-----------------------


    "lv_fonts/Roboto_bold_18.c"
    "lv_fonts/Roboto_bold_24.c"
    "lv_fonts/Roboto_bold_36.c"
    "lv_fonts/Roboto_bold_48.c"

        # ------------My_WIDGETS---------------------
    "my_widgets/w_b_small.c"
    "my_widgets/w_b_big.c"
    "my_widgets/w_drop_label.c"
    "my_widgets/w_time_label.c"
    "my_widgets/w_rad_mask.c"
    "my_widgets/w_scale_img.c"
    "my_widgets/w_scale_marker_img.c"
    "my_widgets/w_pump_on_img.c"
    "my_widgets/w_pump_off_img.c"
    "my_widgets/w_valve_on.c"
    "my_widgets/w_valve_off.c"
    "my_widgets/w_heat_exch.c"
    "my_widgets/w_lock_big_close.c"
    "my_widgets/w_lock_big_open.c"
    "my_widgets/w_in_out_main.c"

    "my_widgets/w_all_inputs_out_down.c"
    "my_widgets/w_analog_out_down.c"
    "my_widgets/w_digital_out_up.c"
    "my_widgets/w_universal_in_down.c"


        #--------Screens-------------------------
    "screens/S_Co/screen_CO.c"
    "screens/S_Gvs/screen_Gvs.c"
    "screens/S_In_Out/1_layer/screen_In_Out.c"
    "screens/S_In_Out/2_layer/screen_In_Out_Second.c"
    "screens/S_Pass/screen_Pass.c"
    "screens/S_Pass/password_screen.c"
    "screens/S_Podp/screen_Podp.c"
    "screens/S_Uv/screen_Uv.c"
    "screens/S_Service/screen_service.c"
    "screens/S_Alarms/screen_alarms.c"


            # --------Other------------------------------
    "main.c"
    "encoder/encoder.c" 
    "encoder/encoder_manager.c"    
    "lv_bg_color/lv_bg_main_screen.c"   
    "dialog_screen/screen_YES_NO/yes_no_screen.c"
    "screen_logic/arc_menu.c"
    "screen_logic/screen_navigation.c"
    "screen_logic/access_control.c"
    "counters/count_test.c"
    "scale_logic_time/time_scale.c"
    "screen_logic/screen_container_manager.c"
    "screen_logic/menu_config.c"
            #---------------Menu_Layer-----------------------
    "menu_layer/main_menu/main_menu.c"
    "menu_layer/In_Out_Menu/In_Out_main_menu.c"
    "menu_layer/CO_Menu/CO_main_menu.c"
    "menu_layer/GVS_Menu/GVS_main_menu.c"
    "menu_layer/CO_Menu/CO_general_menu.c"
    "menu_layer/CO_Menu/CO_general_params.c"
    "menu_layer/CO_Menu/CO_heating_graph_menu.c"
    "menu_layer/CO_Menu/CO_heating_graph_params.c"
    "menu_layer/CO_Menu/CO_pumps_menu.c"
    "menu_layer/CO_Menu/CO_pumps_params.c"
    "menu_layer/CO_Menu/CO_valve_menu.c"
    "menu_layer/CO_Menu/CO_valve_params.c"
    "menu_layer/CO_Menu/CO_manual_menu.c"
    "menu_layer/CO_Menu/CO_manual_params.c"
    "menu_layer/CO_Menu/CO_schedule_menu.c"
    "menu_layer/CO_Menu/CO_schedule_params.c"
    "menu_layer/CO_Menu/CO_alarms_menu.c"
    "menu_layer/CO_Menu/CO_dry_run_menu.c"
    "menu_layer/CO_Menu/CO_dry_run_params.c"
    "menu_layer/CO_Menu/CO_ext_alarm_menu.c"
    "menu_layer/CO_Menu/CO_ext_alarm_params.c"
    "menu_layer/CO_Menu/CO_sensor_break_menu.c"
    "menu_layer/CO_Menu/CO_sensor_break_params.c"
    "menu_layer/CO_Menu/CO_dev_alarm_menu.c"
    "menu_layer/CO_Menu/CO_dev_alarm_params.c"
    "menu_layer/CO_Menu/co_params_limits.c"
    "menu_layer/GVS_Menu/GVS_general_menu.c"
    "menu_layer/GVS_Menu/GVS_general_params.c"
    "menu_layer/GVS_Menu/gvs_params_limits.c"
    "menu_layer/GVS_Menu/GVS_pumps_menu.c"
    "menu_layer/GVS_Menu/GVS_valve_menu.c"
    "menu_layer/GVS_Menu/GVS_valve_params.c"
    "menu_layer/GVS_Menu/gvs_valve_params_limits.c"
    "menu_layer/GVS_Menu/GVS_pumps_params.c"
    "menu_layer/GVS_Menu/gvs_pumps_params_limits.c"
    "menu_layer/GVS_Menu/GVS_manual_menu.c"
    "menu_layer/GVS_Menu/GVS_manual_params.c"
    "menu_layer/GVS_Menu/GVS_schedule_menu.c"
    "menu_layer/GVS_Menu/GVS_schedule_params.c"
    "menu_layer/GVS_Menu/GVS_alarms_menu.c"
    "menu_layer/GVS_Menu/GVS_dry_run_menu.c"
    "menu_layer/GVS_Menu/GVS_dry_run_params.c"
    "menu_layer/GVS_Menu/gvs_dry_run_params_limits.c"
    "menu_layer/GVS_Menu/GVS_ext_alarm_menu.c"
    "menu_layer/GVS_Menu/GVS_ext_alarm_params.c"
    "menu_layer/GVS_Menu/gvs_ext_alarm_params_limits.c"
    "menu_layer/GVS_Menu/GVS_sensor_break_menu.c"
    "menu_layer/GVS_Menu/GVS_sensor_break_params.c"
    "menu_layer/GVS_Menu/gvs_sensor_break_params_limits.c"
    "menu_layer/GVS_Menu/GVS_dev_alarm_menu.c"
    "menu_layer/GVS_Menu/GVS_dev_alarm_params.c"
    "menu_layer/GVS_Menu/gvs_dev_alarm_params_limits.c"



    INCLUDE_DIRS "."
    REQUIRES "nvs_flash"
    PRIV_REQUIRES "cmake_utilities" "lvgl" "esp32_s3_lcd_ev_board" "esp_lvgl_port"
)
